apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: front-end
spec:
  containers:
    - name: nginx
      image: nginx #if not using docker hub repository you need the full name of the repo here
